# <center> NATURAL LANGUAGE PROCESSING </center>
## <center> LAB 8: MINI INFORMATION RETRIEVAL USING WORD EMBEDDINGS </center>
### <center> K Nidhi Sharma, 2148041 </center>

Steps:

1. Extract data
2. Vectorize the data
3. Input query
4. Vectorize query
5. Find cosine similarity
6. Visualize

### Import libraries

In [1]:
import wikipedia
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import numpy as np

### Extracting data from wikipedia

In [2]:
articles=['Data Science','Artificial intelligence','Data Analysis','Data Analytics','Deep Learning']
wiki_lst=[]
title=[]
for article in articles:
   print("loading content: ",article)
   wiki_lst.append(wikipedia.page(article).content)
   title.append(article)
print("examine content")
wiki_lst

loading content:  Data Science
loading content:  Artificial intelligence
loading content:  Data Analysis
loading content:  Data Analytics
loading content:  Deep Learning
examine content


['Data science is an interdisciplinary field that uses scientific methods, processes, algorithms and systems to extract or extrapolate knowledge and insights from noisy, structured and unstructured data, and apply knowledge from data across a broad range of application domains. Data science is related to data mining, machine learning and big data.Data science is a "concept to unify statistics, data analysis, informatics, and their related methods" in order to "understand and analyse actual phenomena" with data. It uses techniques and theories drawn from many fields within the context of mathematics, statistics, computer science, information science, and domain knowledge. However, data science is different from computer science and information science. Turing Award winner Jim Gray imagined data science as a "fourth paradigm" of science (empirical, theoretical, computational, and now data-driven) and asserted that "everything about science is changing because of the impact of information

In [3]:
print("Articles in the data: ")
title

Articles in the data: 


['Data Science',
 'Artificial intelligence',
 'Data Analysis',
 'Data Analytics',
 'Deep Learning']

### Number of articles in data 

In [4]:
print("The number of articles in the data are: ",len(wiki_lst))

The number of articles in the data are:  5


### TF-IDF Vectorization of the articles

In [35]:
tfidf=TfidfVectorizer()
train_tfidf = tfidf.fit_transform(wiki_lst)
train_tfidf

<5x4461 sparse matrix of type '<class 'numpy.float64'>'
	with 7848 stored elements in Compressed Sparse Row format>

### Query 

In [6]:
q=['data science is an upcoming field',"Time series helps in forecasting","Artificial intelligence is the future helping in automation and uses brain mechanism","Natural language processig helps in sentiment analysis", "Data analysis helps in anlaysing the data and find conclusions"]

### Vectorizing query

In [7]:
query_vec1 = tfidf.transform([q[0]])
query_vec2 = tfidf.transform([q[1]])
query_vec3 = tfidf.transform([q[2]])
query_vec4 = tfidf.transform([q[3]])
query_vec5 = tfidf.transform([q[4]])

In [8]:
query_vec1

<1x4461 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [9]:
query_vec2

<1x4461 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [10]:
query_vec3

<1x4461 sparse matrix of type '<class 'numpy.float64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [11]:
query_vec4

<1x4461 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [12]:
query_vec5

<1x4461 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

### Finding similarity of articles based on the query

In [13]:
from sklearn.metrics.pairwise import cosine_similarity

In [14]:
sim1=cosine_similarity(train_tfidf,query_vec1)
print("Document similarity wrt query\n",sim1)

Document similarity wrt query
 [[0.48655559]
 [0.10775152]
 [0.21720191]
 [0.21720191]
 [0.09316248]]


In [15]:
sim2=cosine_similarity(train_tfidf,query_vec2)
print("Document similarity wrt query\n",sim2)

Document similarity wrt query
 [[0.06722673]
 [0.07204206]
 [0.06066597]
 [0.06066597]
 [0.08872197]]


In [16]:
sim2=cosine_similarity(train_tfidf,query_vec2)
print("Document similarity wrt query\n",sim2)

Document similarity wrt query
 [[0.06722673]
 [0.07204206]
 [0.06066597]
 [0.06066597]
 [0.08872197]]


In [17]:
sim3=cosine_similarity(train_tfidf,query_vec3)
print("Document similarity wrt query\n",sim3)

Document similarity wrt query
 [[0.20622322]
 [0.35506041]
 [0.24074273]
 [0.24074273]
 [0.26004774]]


In [18]:
sim4=cosine_similarity(train_tfidf,query_vec4)
print("Document similarity wrt query\n",sim4)

Document similarity wrt query
 [[0.06886679]
 [0.07512733]
 [0.11132513]
 [0.11132513]
 [0.08447507]]


In [19]:
sim5=cosine_similarity(train_tfidf,query_vec5)
print("Document similarity wrt query\n",sim5)

Document similarity wrt query
 [[0.50816749]
 [0.29787884]
 [0.48117785]
 [0.48117785]
 [0.29160781]]


In [26]:
sim1_l = sim1.tolist()
sim1_l = [i[0] for i in sim1_l]
print(sim1_l)

[0.48655558839750435, 0.10775151628412387, 0.21720191289295043, 0.21720191289295043, 0.09316247963054594]


In [27]:
sim2_l = sim2.tolist()
sim2_l = [i[0] for i in sim2_l]
print(sim2_l)

[0.06722673456812264, 0.07204206472292626, 0.06066596503249805, 0.06066596503249805, 0.0887219706887379]


In [28]:
sim3_l = sim3.tolist()
sim3_l = [i[0] for i in sim3_l]
print(sim3_l)

[0.2062232186215656, 0.35506040835622676, 0.24074273182560454, 0.24074273182560454, 0.2600477439796893]


In [29]:
sim4_l = sim4.tolist()
sim4_l = [i[0] for i in sim4_l]
print(sim4_l)

[0.06886678694060433, 0.07512733428057382, 0.11132512705936468, 0.11132512705936468, 0.08447507301532807]


In [30]:
sim5_l = sim5.tolist()
sim5_l = [i[0] for i in sim5_l]
print(sim5_l)

[0.5081674948379791, 0.29787884344324983, 0.4811778497570068, 0.4811778497570068, 0.2916078101384922]


In [33]:
df1 = pd.DataFrame({"q1": sim1_l,"q2":sim2_l,"q3":sim3_l,"q4":sim4_l,"q5":sim5_l}, index=title)

In [34]:
df1.head()

q1        q2        q3        q4        q5
Data Science             0.486556  0.067227  0.206223  0.068867  0.508167
Artificial intelligence  0.107752  0.072042  0.355060  0.075127  0.297879
Data Analysis            0.217202  0.060666  0.240743  0.111325  0.481178
Data Analytics           0.217202  0.060666  0.240743  0.111325  0.481178
Deep Learning            0.093162  0.088722  0.260048  0.084475  0.291608

Upon retriveing the information query wise, 
query1 is highly relevant in data science document, 

query 2 in deep learning,

query3 in AI,

query 4 in DL and 

query 5 in data science document

### With-in document similarity

In [21]:
sim=cosine_similarity(train_tfidf)
pd.DataFrame(sim,index=title,columns=title)

Data Science  Artificial intelligence  Data Analysis  \
Data Science                 1.000000                 0.584218       0.696699   
Artificial intelligence      0.584218                 1.000000       0.771675   
Data Analysis                0.696699                 0.771675       1.000000   
Data Analytics               0.696699                 0.771675       1.000000   
Deep Learning                0.544274                 0.796683       0.712722   

                         Data Analytics  Deep Learning  
Data Science                   0.696699       0.544274  
Artificial intelligence        0.771675       0.796683  
Data Analysis                  1.000000       0.712722  
Data Analytics                 1.000000       0.712722  
Deep Learning                  0.712722       1.000000

1. Artificial intelligence and Deep learning has high similarity
2. Least similarity is between Data Science & Deep learning